data_prep:
  dataset_name: "vehicle_collision_prediction"
  version: "2.0"
  # Features to remove
  remove_columns: ["driver_id"]
  # Categorical encoding configuration
  categorical_columns: ["month"]
  # Missing value imputation configuration - median for numerical, mode for categorical
  imputation_columns: ["time_phoneuse_hours", "count_trip", "miles", "drive_hours", "count_brakes", "count_accelarations", "time_speeding_hours", "highway_miles", "night_drive_hrs", "maximum_speed"]
  # Log transformation configuration - apply log1p to handle right skew
  log_transform_columns: ["miles", "drive_hours", "count_brakes", "count_accelarations"]
  # Scaling configuration - XGBoost handles different scales naturally, minimal scaling needed
  scaling_columns: []
  
feature_prep:
  # Enhanced feature engineering configuration
  create_exposure_normalized: True
  create_risk_ratios: True
  create_composite_risk_score: True
  # Keep original features alongside engineered ones for maximum information
  keep_original_features: True

model_evaluation:
  split_ratio: 0.2
  primary_metric: "Macro PR-AUC"
  cv_folds: 5
  scoring_method: "macro"
  secondary_metrics: ["f1_score", "precision", "recall", "classification_report"]

model:
  model_type: "XGBClassifier"
  model_params:
    n_estimators: 200
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    objective: "multi:softprob"
    eval_metric: "mlogloss"
    num_class: 3
    random_state: 42
  # Hyperparameter tuning configuration - disabled for focused implementation
  hyperparameter_tuning:
    enabled: false
    param_grid: {}
  # Secondary models for comparison
  comparison_models:
    - "RandomForestClassifier"
    - "GradientBoostingClassifier"
  # Feature selection configuration - disabled to use all enhanced features
  feature_selection:
    enabled: false
    method: "RFECV"
    min_features: 5



